kind: pipeline
type: docker
name: build-images

steps:
  - name: golang-node:go1.17.6-node17-alpine3.15
    image: plugins/docker
    settings:
      repo: matseee/golang-node
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      purge: true
      context: golang-node/
      build_args: 
        - GOLANG_VERSION=1.17.6
        - NODE_VERSION=17
        - ALPINE_VERSION=3.15
      tags:
        - latest
        - go1.17.6-node17-alpine3.15