kind: pipeline
type: docker
name: build-images

steps:
  - name: golang-node:go1.19.0-node18.7.0-alpine3.16
    image: plugins/docker
    settings:
      repo: matseee/golang-node
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      purge: true
      dockerfile: golang-node/Dockerfile
      build_args: 
        - GOLANG_VERSION=1.19.0
        - NODE_VERSION=18.7.0
        - ALPINE_VERSION=3.16
      tags:
        - latest
        - go1.19.0-node18.7.0-alpine3.16
  - name: node:node18.7.0-alpine3.16
    image: plugins/docker
    settings:
      repo: matseee/node
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      purge: true
      dockerfile: node/Dockerfile
      build_args:
        - NODE_VERSION=18.7.0
        - ALPINE_VERSION=3.16
      tags:
        - latest
        - node18.7.0-alpine3.16
  - name: openjdk-node:openjdk11-node18.7.0-alpine3.16
    image: plugins/docker
    settings:
      repo: matseee/golang-node
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      purge: true
      dockerfile: openjdk-node/Dockerfile
      build_args: 
        - OPENJDK_VERSION=11
        - NODE_VERSION=18.7.0
        - ALPINE_VERSION=3.16
      tags:
        - latest
        - openjdk11-node18.7.0-alpine3.16