kind: pipeline
type: docker
name: build-images

steps:
  - name: golang-node
    image: plugins/docker:20.14.3
    settings:
      repo: matseee/golang-node
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      purge: true
      dockerfile: golang-node/Dockerfile
      build_args: 
        - GOLANG_VERSION=1.24.2
        - NODE_VERSION=23.11.0
        - ALPINE_VERSION=3.20
      tags:
        - latest
        - go1.24.2-node23.11.0-alpine3.20
  - name: node
    image: plugins/docker:20.14.3
    settings:
      repo: matseee/node
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      purge: true
      dockerfile: node/Dockerfile
      build_args:
        - NODE_VERSION=23.11.0
        - ALPINE_VERSION=3.20
      tags:
        - latest
        - node23.11.0-alpine3.20
  - name: openjdk-node
    image: plugins/docker:20.14.3
    settings:
      repo: matseee/openjdk-node
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      purge: true
      dockerfile: openjdk-node/Dockerfile
      build_args: 
        - OPENJDK_VERSION=25
        - NODE_VERSION=23.11.0
        - ALPINE_VERSION=3.20
      tags:
        - latest
        - openjdk25-node23.11.0-alpine3.20
