kind: pipeline
type: docker
name: build-images

steps:
  - name: golang-node
    image: plugins/docker
    settings:
      repo: matseee/golang-node
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      purge: true
      dockerfile: golang-node/Dockerfile
      build_args: 
        - GOLANG_VERSION=1.21.0
        - NODE_VERSION=18.17.1
        - ALPINE_VERSION=3.18
      tags:
        - latest
        - go1.21.0-node18.17.1-alpine3.18
  - name: node
    image: plugins/docker
    settings:
      repo: matseee/node
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      purge: true
      dockerfile: node/Dockerfile
      build_args:
        - NODE_VERSION=18.17.1
        - ALPINE_VERSION=3.18
      tags:
        - latest
        - node18.17.1-alpine3.18
  - name: openjdk-node
    image: plugins/docker
    settings:
      repo: matseee/openjdk-node
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      purge: true
      dockerfile: openjdk-node/Dockerfile
      build_args: 
        - OPENJDK_VERSION=11
        - NODE_VERSION=18.17.1
        - ALPINE_VERSION=3.16
      tags:
        - latest
        - openjdk19-node18.17.1-alpine3.16